app:
  access-token:
    private: ${ACCESS_TOKEN_PRIVATE_KEY_PATH}
    public: ${ACCESS_TOKEN_PUBLIC_KEY_PATH}
  refresh-token:
    private: ${REFRESH_TOKEN_PRIVATE_KEY_PATH}
    public: ${REFRESH_TOKEN_PUBLIC_KEY_PATH}

spring:
  profiles:
    active:
    - dev
  data:
    mongodb:
      uri: mongodb+srv://oauth:qTZWDcX7ZLwPTFrD@cluster0.ypwa8uf.mongodb.net/?retryWrites=true&w=majority
      database: secure